title: generic-scratch-clone-wars
hero_image: images/banner.png
description: generic-scratch-clone-wars description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: false
interests: ""
technologies: ""
steps:
  - title: Step one
