hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Clone wars
description: Create a game in which you have to save the Earth from space monsters
version: 4.1.0
last_tested: 2018-10-11
steps: 
- title: Introduction
- title: Making a spaceship
- title: Lightning bolts
- title: 'Challenge: fixing the lightning'
  challenge: true
- title: Flying space-hippos
- title: Exploding spaceship
- title: Disappearing hippos
- title: 'Challenge: lives and score'
  challenge: true
- title: Fruit bat
- title: Game over
- title: 'Challenge: improve your game'
  challenge: true