hero_image: images/clone-wars.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Klonkriege
description: Erstelle ein Spiel in dem du den Planet Erde vor den Weltraummonstern retten musst
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: 'games'
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Einführung
- title: Ein Raumschiff bauen
- title: Blitze
- title: Fliegende Weltraum-Nilpfherde
- title: Flughunde!
- title: Game over
- title: 'Aufgabe: Verbessere dein  Spiel'
