---
hero_image: images/clone-wars.png
theme: fioletowy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Atak klonów
description: Naucz się, jak stworzyć grę, w której musisz uratować Ziemię przed potworami z kosmosu.
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: gry
technologies: scratch
site_areas: projekty
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Atak klonów
  - 
    title: Czego będziesz potrzebować
  - 
    title: Budowanie statku kosmicznego
  - 
    title: Błyskawice
  - 
    title: Latające kosmo-hipopotamy
  - 
    title: Eksplodujący statek kosmiczny
  - 
    title: Znikające hipopotamy
  - 
    title: Owocowy nietoperz
  - 
    title: Koniec gry
  - 
    title: 'Wyzwanie: udoskonal swoją grę'
