---
hero_image: images/clone-wars.png
theme: viola
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Guerre dei Cloni
description: Crea un gioco in cui dovrai salvare la Terra dai mostri dello spazio
original_url: https://codeclubprojects.org/it-IT/scratch/clone-wars
interests: giochi
technologies: scratch
site_areas: progetti
hardware: ''
software: scratch
version: 4
last_tested: 01/01/2017
steps:
  - 
    title: Introduzione
  - 
    title: Creare un'Astronave
  - 
    title: Fulmini
  - 
    title: Ippopotami Spaziali Volanti
  - 
    title: Pipistrelli della Frutta!
  - 
    title: Game over
  - 
    title: 'Sfida: Migliora il tuo gioco'
  - 
    title: Volpe volante
  - 
    title: Fine gioco
  - 
    title: 'Sfida: migliora il tuo gioco'
